import React, { useState, useEffect } from 'react';
import {
  Box,
  Typography,
  Button,
  Paper,
  IconButton,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Alert,
  Snackbar,
  Chip,
  Grid,
  Card,
  CardContent,
  Collapse,
} from '@mui/material';
import {
  Add as AddIcon,
  Edit as EditIcon,
  Delete as DeleteIcon,
  School as SchoolIcon,
  ExpandMore as ExpandMoreIcon,
  ExpandLess as ExpandLessIcon,
} from '@mui/icons-material';
import { classroomAPI } from '../services/api';

const ClassroomManagement = () => {
  const [classrooms, setClassrooms] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState(null);
  const [open, setOpen] = useState(false);
  const [editingClassroom, setEditingClassroom] = useState(null);
  const [formData, setFormData] = useState({
    roomName: '',
    roomCode: '',
    roomType: '',
    capacity: '',
  });
  const [roomCodeAutoGenerated, setRoomCodeAutoGenerated] = useState(false);
  const [expandedCards, setExpandedCards] = useState(new Set());

  const roomTypes = ['Chemistry Lab', 'Biology Lab', 'Physics Lab', 'Computer Lab',  'Lecture Room', 'Physical Education Area'];

  const toggleCard = (id) => {
    setExpandedCards(prev => {
      const newSet = new Set(prev);
      if (newSet.has(id)) {
        newSet.delete(id);
      } else {
        newSet.add(id);
      }
      return newSet;
    });
  };

  useEffect(() => {
    fetchClassrooms();
  }, []);

  const fetchClassrooms = async () => {
    try {
      setLoading(true);
      const response = await classroomAPI.getAll();
      setClassrooms(response.data);
      setError(null);
    } catch (err) {
      setError('Failed to fetch classrooms');
    } finally {
      setLoading(false);
    }
  };

  const generateRoomCode = (roomName) => {
    if (!roomName || !roomName.trim()) return '';
    
    let code = roomName.trim();
    
    // Try to extract existing code pattern (letters followed by numbers)
    // Examples: "Room 101" -> "R101", "LAB 1" -> "LAB1", "Chemistry Lab 2" -> "CL2"
    const codePattern = /([A-Za-z]+)\s*(\d+)/i;
    const match = code.match(codePattern);
    if (match) {
      const letters = match[1].toUpperCase();
      const numbers = match[2];
      // Use up to 3 letters + numbers
      return letters.substring(0, 3) + numbers;
    }
    
    // Extract all uppercase letters and numbers (for codes like "R101", "LAB1A")
    const lettersAndNumbers = code.match(/[A-Z0-9]+/gi);
    if (lettersAndNumbers && lettersAndNumbers.length > 0) {
      const extracted = lettersAndNumbers.join('').toUpperCase();
      if (extracted.length > 0 && extracted.length <= 12) {
        return extracted;
      } else if (extracted.length > 12) {
        // If too long, take first part
        return extracted.substring(0, 10);
      }
    }
    
    // Fallback: Create code from first letters of words + numbers
    const words = code.split(/\s+/);
    let result = '';
    
    // Take first letter of each word (up to 3 words for brevity)
    words.slice(0, 3).forEach(word => {
      const firstLetter = word.match(/[A-Za-z]/);
      if (firstLetter) {
        result += firstLetter[0].toUpperCase();
      }
    });
    
    // Extract any numbers from the original string and append
    const numbers = code.match(/\d+/g);
    if (numbers && numbers.length > 0) {
      result += numbers.join('');
    }
    
    // If we have a result, return it (limit to 10 chars)
    if (result) {
      return result.substring(0, 10);
    }
    
    // Last resort: uppercase first 6 characters, removing spaces
    return code.substring(0, 6).toUpperCase().replace(/\s+/g, '').replace(/[^A-Z0-9]/g, '');
  };

  const handleOpen = (classroom = null) => {
    if (classroom) {
      setEditingClassroom(classroom);
      setFormData({
        roomName: classroom.roomName,
        roomCode: classroom.roomCode || '',
        roomType: classroom.roomType,
        capacity: classroom.capacity.toString(),
      });
      setRoomCodeAutoGenerated(false);
    } else {
      setEditingClassroom(null);
      setFormData({
        roomName: '',
        roomCode: '',
        roomType: '',
        capacity: '',
      });
      setRoomCodeAutoGenerated(false);
    }
    setOpen(true);
  };

  const handleClose = () => {
    setOpen(false);
    setEditingClassroom(null);
    setFormData({
      roomName: '',
      roomCode: '',
      roomType: '',
      capacity: '',
    });
    setRoomCodeAutoGenerated(false);
  };

  const handleSubmit = async () => {
    try {
      // Validate required fields
      if (!formData.roomName.trim()) {
        setError('Room name is required');
        return;
      }
      if (!formData.roomCode.trim()) {
        setError('Room code is required');
        return;
      }
      if (!formData.roomType) {
        setError('Room type is required');
        return;
      }
      if (!formData.capacity || formData.capacity <= 0) {
        setError('Capacity must be a positive number');
        return;
      }
  

      const classroomData = {
        ...formData,
        capacity: parseInt(formData.capacity),
      };

      if (editingClassroom) {
        await classroomAPI.update(editingClassroom.id, classroomData);
        setSuccess('Classroom updated successfully');
      } else {
        await classroomAPI.create(classroomData);
        setSuccess('Classroom created successfully');
      }

      handleClose();
      fetchClassrooms();
    } catch (err) {
      setError(editingClassroom ? 'Failed to update classroom' : 'Failed to create classroom');
    }
  };

  const handleDelete = async (id) => {
    if (window.confirm('Are you sure you want to delete this classroom?')) {
      try {
        await classroomAPI.delete(id);
        setSuccess('Classroom deleted successfully');
        fetchClassrooms();
      } catch (err) {
        setError('Failed to delete classroom');
      }
    }
  };

  const handleChange = (field) => (event) => {
    const value = event.target.value;
    
    setFormData(prev => {
      const newData = {
      ...prev,
        [field]: value,
      };
      
      // Auto-generate room code when room name changes
      if (field === 'roomName') {
        // Only auto-generate if:
        // 1. It's a new classroom (not editing), OR
        // 2. The room code was previously auto-generated in this session, OR
        // 3. The room code field is currently empty
        if (!editingClassroom || roomCodeAutoGenerated || !prev.roomCode.trim()) {
          const generatedCode = generateRoomCode(value);
          if (generatedCode) {
            newData.roomCode = generatedCode;
            setRoomCodeAutoGenerated(true);
          } else if (roomCodeAutoGenerated) {
            // If generated code is empty and it was auto-generated, clear it
            newData.roomCode = '';
          }
        }
      }
      
      // Track if user manually changes room code (user override)
      if (field === 'roomCode') {
        // If user cleared the code, allow auto-generation again
        if (value.trim().length === 0 && prev.roomCode.trim().length > 0) {
          setRoomCodeAutoGenerated(false);
        } else if (value.trim().length > 0) {
          // User typed something - mark as manually entered
          setRoomCodeAutoGenerated(false);
        }
      }
      
      return newData;
    });
  };

  return (
    <Box>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
        <Typography variant="h4">
          <SchoolIcon sx={{ mr: 1, verticalAlign: 'middle' }} />
          Classroom Management
        </Typography>
        <Button
          variant="contained"
          startIcon={<AddIcon />}
          onClick={() => handleOpen()}
        >
          Add Classroom
        </Button>
      </Box>

      {loading ? (
        <Typography>Loading...</Typography>
      ) : classrooms.length === 0 ? (
        <Paper sx={{ p: 4, textAlign: 'center' }}>
          <Typography variant="h6" color="textSecondary">
            No classrooms found. Click "Add Classroom" to get started.
          </Typography>
        </Paper>
      ) : (
        <Grid container spacing={2}>
          {classrooms.map((classroom) => {
            const isExpanded = expandedCards.has(classroom.id);
            return (
              <Grid item xs={12} sm={6} md={4} lg={3} key={classroom.id}>
                <Card
                  sx={{
                    transition: 'all 0.3s ease-in-out',
                    borderLeft: '4px solid',
                    borderLeftColor: 'primary.main',
                    cursor: 'pointer',
                    '&:hover': {
                      transform: 'translateY(-2px)',
                      boxShadow: 4,
                    },
                  }}
                  onClick={() => toggleCard(classroom.id)}
                >
                  <CardContent
                    sx={{
                      p: 2,
                      '&:last-child': { pb: isExpanded ? 2 : 2 },
                    }}
                  >
                    {/* Collapsed view - just room name */}
                    <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                      <Typography
                        variant="h6"
                        component="div"
                        sx={{
                          fontWeight: 600,
                          color: 'primary.main',
                          flex: 1,
                        }}
                      >
                        {classroom.roomName}
                      </Typography>
                      <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
                        <IconButton
                          size="small"
                          onClick={(e) => {
                            e.stopPropagation();
                            toggleCard(classroom.id);
                          }}
                          sx={{ ml: 1 }}
                        >
                          {isExpanded ? <ExpandLessIcon /> : <ExpandMoreIcon />}
                    </IconButton>
                      </Box>
                    </Box>

                    {/* Expanded view - all details */}
                    <Collapse in={isExpanded} timeout="auto">
                      <Box sx={{ mt: 2, pt: 2, borderTop: '1px solid', borderColor: 'divider' }}>
                        <Grid container spacing={2}>
                          <Grid item xs={12}>
                            <Box>
                              <Typography
                                variant="caption"
                                color="textSecondary"
                                sx={{
                                  textTransform: 'uppercase',
                                  fontWeight: 600,
                                  letterSpacing: 0.5,
                                  fontSize: '0.7rem',
                                }}
                              >
                                Room Code
                              </Typography>
                              <Typography variant="body2" fontWeight={500} sx={{ mt: 0.5 }}>
                                {classroom.roomCode || '-'}
                              </Typography>
                            </Box>
                          </Grid>
                          <Grid item xs={12}>
                            <Box>
                              <Typography
                                variant="caption"
                                color="textSecondary"
                                sx={{
                                  textTransform: 'uppercase',
                                  fontWeight: 600,
                                  letterSpacing: 0.5,
                                  fontSize: '0.7rem',
                                }}
                              >
                                Type
                              </Typography>
                              <Box sx={{ mt: 0.5 }}>
                                <Chip
                                  label={classroom.roomType}
                                  color="primary"
                                  size="small"
                                  sx={{ fontWeight: 500 }}
                                />
                              </Box>
                            </Box>
                          </Grid>
                          <Grid item xs={12}>
                            <Box>
                              <Typography
                                variant="caption"
                                color="textSecondary"
                                sx={{
                                  textTransform: 'uppercase',
                                  fontWeight: 600,
                                  letterSpacing: 0.5,
                                  fontSize: '0.7rem',
                                }}
                              >
                                Capacity
                              </Typography>
                              <Typography variant="body2" fontWeight={500} sx={{ mt: 0.5 }}>
                                {classroom.capacity} students
                              </Typography>
                            </Box>
                          </Grid>
                          <Grid item xs={12}>
                            <Box sx={{ display: 'flex', gap: 1, mt: 1 }}>
                              <Button
                                variant="outlined"
                                size="small"
                                startIcon={<EditIcon />}
                                onClick={(e) => {
                                  e.stopPropagation();
                                  handleOpen(classroom);
                                }}
                                color="primary"
                                fullWidth
                              >
                                Edit
                              </Button>
                              <Button
                                variant="outlined"
                                size="small"
                                startIcon={<DeleteIcon />}
                                onClick={(e) => {
                                  e.stopPropagation();
                                  handleDelete(classroom.id);
                                }}
                                color="error"
                                fullWidth
                              >
                                Delete
                              </Button>
                            </Box>
                          </Grid>
                        </Grid>
                      </Box>
                    </Collapse>
                  </CardContent>
                </Card>
              </Grid>
            );
          })}
        </Grid>
      )}

      <Dialog open={open} onClose={handleClose} maxWidth="sm" fullWidth>
        <DialogTitle>
          {editingClassroom ? 'Edit Classroom' : 'Add New Classroom'}
        </DialogTitle>
        <DialogContent>
          <Grid container spacing={2} sx={{ mt: 1 }}>
            <Grid item xs={12} sm={6}>
              <TextField
                label="Room Name"
                value={formData.roomName}
                onChange={handleChange('roomName')}
                fullWidth
                required
              />
            </Grid>
            <Grid item xs={12} sm={6}>
              <TextField
                label="Room Code"
                value={formData.roomCode}
                onChange={handleChange('roomCode')}
                fullWidth
                required
                placeholder="e.g., R101, LAB1"
                helperText={roomCodeAutoGenerated ? "Auto-generated from room name" : "Enter room code or it will be auto-generated"}
              />
            </Grid>
            <Grid item xs={12} sm={6}>
              <FormControl fullWidth required>
                <InputLabel>Room Type</InputLabel>
                <Select
                  value={formData.roomType}
                  onChange={handleChange('roomType')}
                  label="Room Type"
                >
                  {roomTypes.map((type) => (
                    <MenuItem key={type} value={type}>
                      {type}
                    </MenuItem>
                  ))}
                </Select>
              </FormControl>
            </Grid>
            <Grid item xs={12} sm={6}>
              <TextField
                label="Capacity"
                type="number"
                value={formData.capacity}
                onChange={handleChange('capacity')}
                fullWidth
                required
                inputProps={{ min: 1 }}
              />
            </Grid>
            
          </Grid>
        </DialogContent>
        <DialogActions>
          <Button onClick={handleClose}>Cancel</Button>
          <Button onClick={handleSubmit} variant="contained">
            {editingClassroom ? 'Update' : 'Create'}
          </Button>
        </DialogActions>
      </Dialog>

      <Snackbar
        open={!!error}
        autoHideDuration={6000}
        onClose={() => setError(null)}
      >
        <Alert severity="error" onClose={() => setError(null)}>
          {error}
        </Alert>
      </Snackbar>

      <Snackbar
        open={!!success}
        autoHideDuration={6000}
        onClose={() => setSuccess(null)}
      >
        <Alert severity="success" onClose={() => setSuccess(null)}>
          {success}
        </Alert>
      </Snackbar>
    </Box>
  );
};

export default ClassroomManagement;
